spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dscatalog
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        hbm2ddl:
#          delimiter: ";"
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
    hibernate:
      ddl-auto: none